# Generated by Django 4.1.5 on 2023-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_worker_shop_remove_worker_user_delete_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
