# Generated by Django 4.2.1 on 2023-05-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_statistic_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='dashboard.stock'),
        ),
    ]
